### ISSUE TITLE
Missing util.h

### ISSUE THREAD

**Issue by asalamon74** [mikemayer67/xbattle#1]
Hi, 
commandline.cc includes "util.h" but the util.h file is missing.

**Comment by mikemayer67** [comment]
I got sidetracked with "real" work.  I will take a look at this shortly.
Please note, however, that this entire project is in a far from usable state.

**Comment by mikemayer67** [comment]
Removed the inclusion of util.h from commandline.cc
I failed to remove this when I consolidated util.h with another header.
I didn't catch the error because I just happened to have a different util.h in my include path
Thank you for the catch!
